### ISSUE TITLE
How to get any results back

### ISSUE THREAD

**Issue by usarid** [alchemycs/spheron#3]
This is a great little project and it's been working well for setting values: changing colors, rolling, etc. But how do I get back values? For example, can you give any example of how getRGB would be used? Is there some callback needed?

Thanks!

**Comment by alchemycs** [comment]
Hi there,

Thanks for your interest, this is something else I'll need to put in the documentation! :smile: 

Spheron uses an event model. You can tell the spheron instance to always emit an acknowledgement, or on a call by call basis in the `options` object: 

```
var sampleSequenceId = 42;
var s = sphero();
//s.requestAcknowledgement(true); //Always request acknowledgements
s.open('/dev/...');
s.on('message', function(packet) {
  if (packet.SEQ == sampleSequenceId) {
    console.log('Woo Hoo!', packet);
  }
});

s.on('open', function() {
  s.getRGB({
    requestAcknowledgement:true, /* or false, this will overide the default set by s.requestAcknowledgement()  */
    SEQ:sampleSequenceId});
});

```

The packet in the event is raw at the moment, so you will need to checkout the [Sphero API](https://github.com/orbotix/DeveloperResources/blob/master/docs/Sphero_API_1.50.pdf) for the format - I hope to address this in the future so that each response has a specialised structure as well as the raw response.

You can also configure spheron to _always_ request an acknowledgement by doing `s.requestAcknowledgement(true)`. However you will need to set the `SEQ` in the options for each call. Alternatively you could filter each data event by checking the `CID` and `DID` properties on the event packet to match against the call type. If you don't set the `SEQ` property it will be `0x00`

P.S. I replied at work, so no access to my Sphero to double check. I'll try and get something more complete for you a little later.

**Comment by alchemycs** [comment]
I had a mistake in the previous comment but have edited it: there are 3 events you can listen to for various responses from sphero:

`s.on('message', function(m) {..});` will trigger only on messages - so responses to commands.

`s.on('notification', function(n) {..});` will trigger only on notifications - these are asynchronous that you can turn on for data streaming, or when power is getting low

`s.on('packet', function(p) {..});` will trigger on both messages and notifications, you can inspect the packet yourself to determine what it is meant to be.

Hope that helps somewhat.

**Comment by usarid** [comment]
Thanks -- after some futzing around I managed to get it to work, though it's unpredictable -- sometimes no packet events are triggered, then later it all works.

Check out my little play project where I use your library to build a REST API, described via RAML (http://raml.org), on the Sphero: https://github.com/usarid/spherest
